
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kevin
 */
public class AgentPasswordWindow extends javax.swing.JFrame {
     
private static InfDB idb;

    /**
     * Creates new form AdminPasswordWindow
     */
   

     public AgentPasswordWindow(InfDB idb) {
        initComponents();
        this.idb = idb;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nuvarandeLösenordRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nyttLösenordRuta = new javax.swing.JTextField();
        bekräftaLösenordKnapp = new javax.swing.JButton();
        tillbakaKnapp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        användarnamnRuta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Ange nytt lösenord");

        nuvarandeLösenordRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuvarandeLösenordRutaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Ange nuvarande lösenord");

        bekräftaLösenordKnapp.setText("Bekräfta");
        bekräftaLösenordKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bekräftaLösenordKnappActionPerformed(evt);
            }
        });

        tillbakaKnapp.setText("Tillbaka");
        tillbakaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tillbakaKnappActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Användarnamn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tillbakaKnapp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(nyttLösenordRuta)
                            .addComponent(jLabel1)
                            .addComponent(nuvarandeLösenordRuta)
                            .addComponent(bekräftaLösenordKnapp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(användarnamnRuta))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(användarnamnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuvarandeLösenordRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(nyttLösenordRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bekräftaLösenordKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(tillbakaKnapp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuvarandeLösenordRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuvarandeLösenordRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuvarandeLösenordRutaActionPerformed

    private void bekräftaLösenordKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bekräftaLösenordKnappActionPerformed
        if (Validation.textEmptyValidation(användarnamnRuta) && Validation.textEmptyValidation(nuvarandeLösenordRuta) && Validation.textEmptyValidation(nyttLösenordRuta))
       
        {
            //Hämtar användarnamn och lösenord som användare matar in.
            String userNameInut = användarnamnRuta.getText();
            String currentPasswordInput = nuvarandeLösenordRuta.getText();
            String newPassWordInput = nyttLösenordRuta.getText();

            try {
                //Hämtar in användarnamn och lösenord från databasen.
                String username = idb.fetchSingle("SELECT AGENT_ID FROM AGENT WHERE AGENT_ID = " + userNameInut);
                String password = idb.fetchSingle("SELECT LOSENORD FROM AGENT WHERE AGENT_ID = " + userNameInut);

                // Jämför BÅDE användarnamn (agent_ID) och lösenord mellan värderna från databasen och det användare matat in.
                //Om det stämmer överrens så uppdateras lösenordet.
                if (userNameInut.equals(username) && currentPasswordInput.equals(password)) {
                    idb.update("UPDATE AGENT SET LOSENORD= " + "'" + newPassWordInput + "'" + "WHERE AGENT_ID= " + userNameInut);
                    JOptionPane.showMessageDialog(null, "Lösenordet har ändrats!");
                    setVisible(false);

                } else {
                    //Felmeddelande att användarnamn eller lösenord inte stämmer överrens.
                    JOptionPane.showMessageDialog(null, "Fel lösenord eller användarnamn!");
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Ett fel inträffade!");
            }
        }
    }//GEN-LAST:event_bekräftaLösenordKnappActionPerformed

    private void tillbakaKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaKnappActionPerformed
                setVisible(false);
    }//GEN-LAST:event_tillbakaKnappActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField användarnamnRuta;
    private javax.swing.JButton bekräftaLösenordKnapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nuvarandeLösenordRuta;
    private javax.swing.JTextField nyttLösenordRuta;
    private javax.swing.JButton tillbakaKnapp;
    // End of variables declaration//GEN-END:variables
}
